# Generated by Django 5.0.6 on 2024-05-16 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_app.talent')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('contact_details', models.CharField(max_length=100)),
                ('skills', models.TextField()),
                ('brief_description', models.TextField()),
                ('profile_pic', models.ImageField(upload_to='profile_pics/')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('talents', models.ManyToManyField(to='social_app.talent')),
                ('videos', models.ManyToManyField(to='social_app.video')),
            ],
        ),
    ]
