# Generated by Django 4.1.13 on 2024-05-19 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='talent',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='talents',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='videos',
        ),
        migrations.DeleteModel(
            name='Talent',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
