# Generated by Django 4.1.13 on 2024-05-20 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0003_login_table_remove_candidate_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_app.login_table'),
        ),
        migrations.AlterField(
            model_name='director',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_app.login_table'),
        ),
    ]
