# Generated by Django 4.1.13 on 2024-05-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0004_alter_candidate_login_alter_director_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='id_file',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
