# Generated by Django 4.1.13 on 2024-05-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0005_director_id_file_director_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Talents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talent', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Talent',
                'verbose_name_plural': 'Talents',
            },
        ),
        migrations.AlterField(
            model_name='candidate',
            name='profile_pic',
            field=models.ImageField(upload_to=''),
        ),
    ]
