# Generated by Django 4.1.13 on 2024-05-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0008_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
