# Generated by Django 4.1.13 on 2024-05-29 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0010_alter_post_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='candidate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='social_app.candidate'),
        ),
    ]
