# Generated by Django 4.1.13 on 2024-05-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0011_post_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='candidate',
        ),
        migrations.AddField(
            model_name='candidate',
            name='location',
            field=models.CharField(blank=True, default=1, max_length=100, null=True),
        ),
    ]
