# Generated by Django 4.1.13 on 2024-05-29 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0012_remove_post_candidate_candidate_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='talent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social_app.talents'),
        ),
    ]
