# Generated by Django 4.1.13 on 2024-05-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0013_alter_post_talent_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
