# Generated by Django 4.1.13 on 2024-06-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_app', '0014_post_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_table',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
